var ca="function"==typeof Object.defineProperties?Object.defineProperty:function(c,b,a){if(a.get||a.set)throw new TypeError("ES3 does not support getters and setters.");c!=Array.prototype&&c!=Object.prototype&&(c[b]=a.value)},G="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;function K(){K=function(){};G.Symbol||(G.Symbol=da)}var ja=0;function da(c){return"jscomp_symbol_"+(c||"")+ja++}
function L(){K();var c=G.Symbol.iterator;c||(c=G.Symbol.iterator=G.Symbol("iterator"));"function"!=typeof Array.prototype[c]&&ca(Array.prototype,c,{configurable:!0,writable:!0,value:function(){return ka(this)}});L=function(){}}function ka(c){var b=0;return la(function(){return b<c.length?{done:!1,value:c[b++]}:{done:!0}})}function la(c){L();c={next:c};c[G.Symbol.iterator]=function(){return this};return c}function O(c){L();K();L();var b=c[Symbol.iterator];return b?b.call(c):ka(c)}
function V(c,b){function a(){}a.prototype=b.prototype;c.prototype=new a;c.prototype.constructor=c;for(var d in b)if(Object.defineProperties){var e=Object.getOwnPropertyDescriptor(b,d);e&&Object.defineProperty(c,d,e)}else c[d]=b[d]}function W(c,b){if(b){var a=G;c=c.split(".");for(var d=0;d<c.length-1;d++){var e=c[d];e in a||(a[e]={});a=a[e]}c=c[c.length-1];d=a[c];b=b(d);b!=d&&null!=b&&ca(a,c,{configurable:!0,writable:!0,value:b})}}
W("Promise",function(c){function b(a){this.H=0;this.V=void 0;this.F=[];var b=this.N();try{a(b.resolve,b.reject)}catch(h){b.reject(h)}}function a(){this.j=null}if(c)return c;a.prototype.ca=function(a){null==this.j&&(this.j=[],this.qa());this.j.push(a)};a.prototype.qa=function(){var a=this;this.da(function(){a.Aa()})};var d=G.setTimeout;a.prototype.da=function(a){d(a,0)};a.prototype.Aa=function(){for(;this.j&&this.j.length;){var a=this.j;this.j=[];for(var b=0;b<a.length;++b){var d=a[b];delete a[b];
try{d()}catch(k){this.ra(k)}}}this.j=null};a.prototype.ra=function(a){this.da(function(){throw a;})};b.prototype.N=function(){function a(a){return function(e){d||(d=!0,a.call(b,e))}}var b=this,d=!1;return{resolve:a(this.Ia),reject:a(this.U)}};b.prototype.Ia=function(a){if(a===this)this.U(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof b)this.Ja(a);else{var d;a:switch(typeof a){case "object":d=null!=a;break a;case "function":d=!0;break a;default:d=!1}d?this.Ha(a):this.ia(a)}};
b.prototype.Ha=function(a){var b=void 0;try{b=a.then}catch(h){this.U(h);return}"function"==typeof b?this.Ka(b,a):this.ia(a)};b.prototype.U=function(a){this.la(2,a)};b.prototype.ia=function(a){this.la(1,a)};b.prototype.la=function(a,b){if(0!=this.H)throw Error("Cannot settle("+a+", "+b|"): Promise already settled in state"+this.H);this.H=a;this.V=b;this.Ba()};b.prototype.Ba=function(){if(null!=this.F){for(var a=this.F,b=0;b<a.length;++b)a[b].call(),a[b]=null;this.F=null}};var e=new a;b.prototype.Ja=
function(a){var b=this.N();a.M(b.resolve,b.reject)};b.prototype.Ka=function(a,b){var d=this.N();try{a.call(b,d.resolve,d.reject)}catch(k){d.reject(k)}};b.prototype.then=function(a,d){function e(a,b){return"function"==typeof a?function(b){try{c(a(b))}catch(q){f(q)}}:b}var c,f,g=new b(function(a,b){c=a;f=b});this.M(e(a,c),e(d,f));return g};b.prototype.catch=function(a){return this.then(void 0,a)};b.prototype.M=function(a,b){function d(){switch(c.H){case 1:a(c.V);break;case 2:b(c.V);break;default:throw Error("Unexpected state: "+
c.H);}}var c=this;null==this.F?e.ca(d):this.F.push(function(){e.ca(d)})};b.resolve=function(a){return a instanceof b?a:new b(function(b){b(a)})};b.reject=function(a){return new b(function(b,d){d(a)})};b.race=function(a){return new b(function(d,c){for(var e=O(a),f=e.next();!f.done;f=e.next())b.resolve(f.value).M(d,c)})};b.all=function(a){var d=O(a),c=d.next();return c.done?b.resolve([]):new b(function(a,e){function f(b){return function(d){g[b]=d;h--;0==h&&a(g)}}var g=[],h=0;do g.push(void 0),h++,b.resolve(c.value).M(f(g.length-
1),e),c=d.next();while(!c.done)})};b.$jscomp$new$AsyncExecutor=function(){return new a};return b});function ma(c,b){L();c instanceof String&&(c+="");var a=0,d={next:function(){if(a<c.length){var e=a++;return{value:b(e,c[e]),done:!1}}d.next=function(){return{done:!0,value:void 0}};return d.next()}};d[Symbol.iterator]=function(){return d};return d}
W("Object.assign",function(c){return c?c:function(b,a){for(var d=1;d<arguments.length;d++){var c=arguments[d];if(c)for(var f in c)Object.prototype.hasOwnProperty.call(c,f)&&(b[f]=c[f])}return b}});W("Array.prototype.entries",function(c){return c?c:function(){return ma(this,function(b,a){return[b,a]})}});
(function(c){function b(d){if(a[d])return a[d].a;var e=a[d]={a:{},id:d,loaded:!1};c[d].call(e.a,e,e.a,b);e.loaded=!0;return e.a}var a={};b.fb=c;b.Ta=a;b.p="";return b(0)})([function(c,b,a){b=a(2);c=b.b;b=b.g;a=a(41);var d=document.getElementById("app-container");b(c(a,null),d.parentNode,d)},function(c,b,a){var d=a(3),e=a(12);c.a=function(a){return function h(b,c){switch(arguments.length){case 0:return h;case 1:return e(b)?h:d(function(d){return a(b,d)});default:return e(b)&&e(c)?h:e(b)?d(function(b){return a(b,
c)}):e(c)?d(function(d){return a(b,d)}):a(b,c)}}}},function(c,b){!function(a,d){d(b)}(this,function(a){function b(a){return ea[a]||(ea[a]=a.toLowerCase())}function c(a,b,d){this.nodeName=a;this.attributes=b;this.children=d;this.key=b&&b.key}function f(a,b){var d,e,p,f=[];for(p=arguments.length;2<p--;)D.push(arguments[p]);b&&b.children&&(D.length||D.push(b.children),delete b.children);for(;D.length;)if((e=D.pop())instanceof Array)for(p=e.length;p--;)D.push(e[p]);else if(null!=e&&!1!==e){if("number"==
typeof e||!0===e)e=String(e);(p="string"==typeof e)&&d?f[f.length-1]+=e:(f.push(e),d=p)}d=new c(a,b||void 0,f);x.Qa&&x.Qa(d);return d}function g(a,b){if(b)for(var d in b)a[d]=b[d];return a}function h(a){return"function"==typeof a}function k(a){return"string"==typeof a}function l(a,b,d){var c=b.split(".");return function(b){var e=b&&b.target||this,p={},f=p;if(k(d))for(var e=d.split("."),g=0;g<e.length&&b;g++)b=b[e[g]];else b=e.nodeName?e.type.match(/^che|rad/)?e.checked:e.value:b;for(e=0;e<c.length-
1;e++)f=f[c[e]]||(f[c[e]]=!e&&a.state[c[e]]||{});f[c[e]]=b;a.G(p)}}function n(a){!a.K&&(a.K=!0)&&1==X.push(a)&&(x.Wa||na)(m)}function m(){var a,b=X;for(X=[];a=b.pop();)a.K&&C(a)}function E(a){return(a=a&&a.nodeName)&&h(a)&&!(a.prototype&&a.prototype.g)}function H(a,b){return a.nodeName(z(a),b||oa)}function q(a,d){return a.ka===d||b(a.nodeName)===b(d)}function z(a){var b=g({},a.attributes);b.children=a.children;if(a=a.nodeName.Xa)for(var d in a)void 0===b[d]&&(b[d]=a[d]);return b}function A(a){var b=
a.parentNode;b&&b.removeChild(a)}function w(a,d,c,e,f){"className"===d&&(d="class");if("class"===d&&e&&"object"==typeof e){var p="",g;for(g in e)e[g]&&(p&&(p+=" "),p+=g);e=p}if("key"!==d)if("class"!==d||f)if("style"===d){if(!e||k(e)||k(c))a.style.cssText=e||"";if(e&&"object"==typeof e){if(!k(c))for(var t in c)t in e||(a.style[t]="");for(t in e)a.style[t]="number"!=typeof e[t]||pa[t]?e[t]:e[t]+"px"}}else if("dangerouslySetInnerHTML"===d)a.innerHTML=e&&e.ma||"";else if("o"==d[0]&&"n"==d[1])c=a.$||(a.$=
{}),d=b(d.substring(2)),e?c[d]||a.addEventListener(d,M,!!fa[d]):c[d]&&a.removeEventListener(d,M,!!fa[d]),c[d]=e;else if("list"!==d&&"type"!==d&&!f&&d in a){try{a[d]=null==e?"":e}catch(qa){}null!=e&&!1!==e||a.removeAttribute(d)}else c=f&&d.match(/^xlink\:?(.+)/),null==e||!1===e?c?a.removeAttributeNS("http://www.w3.org/1999/xlink",b(c[1])):a.removeAttribute(d):"object"==typeof e||h(e)||(c?a.setAttributeNS("http://www.w3.org/1999/xlink",b(c[1]),e):a.setAttribute(d,e));else a.className=e||""}function M(a){return this.$[a.type](x.event&&
x.event(a)||a)}function Q(a,d){var e=b(a);a=R[e]&&R[e].pop()||(d?document.createElementNS("http://www.w3.org/2000/svg",a):document.createElement(a));a.ka=e;return a}function t(){for(var a;a=ga.pop();)x.oa&&x.oa(a),a.B&&a.B()}function y(a,b,d,e,c,f){Y++||(J=c instanceof SVGElement,S=a&&!(F in a));a=P(a,b,d,e);c&&a.parentNode!==c&&c.appendChild(a);--Y||(S=!1,f||t());return a}function P(a,b,d,e){for(var c=b&&b.attributes;E(b);)b=H(b,d);null==b&&(b="");if(k(b))return a&&a instanceof Text?a.nodeValue!=
b&&(a.nodeValue=b):(a&&N(a),a=document.createTextNode(b)),a[F]=!0,a;if(h(b.nodeName)){var c=a,f=b,g=c&&c.f,t=c,p=g&&c.A===f.nodeName,l=p;for(a=z(f);g&&!l&&(g=g.aa);)l=g.constructor===f.nodeName;g&&l&&(!e||g.f)?(T(g,a,3,d,e),c=g.h):(g&&!p&&(U(g,!0),c=t=null),g=ha(f.nodeName,a,d),c&&!g.l&&(g.l=c,t=null),T(g,a,1,d,e),c=g.h,t&&c!==t&&(t.f=null,N(t)));return c}var f=a,m=String(b.nodeName),g=J,t=b.children;J="svg"===m?!0:"foreignObject"===m?!1:J;if(!a)f=Q(m,J);else if(!q(a,m)){for(f=Q(m,J);a.firstChild;)f.appendChild(a.firstChild);
a.parentNode&&a.parentNode.replaceChild(f,a);N(a)}m=f.firstChild;a=f[F];if(!a){f[F]=a={};for(var n=f.attributes,y=n.length;y--;)a[n[y].name]=n[y].value}n=f;b=b.attributes;var y=a,B;for(B in y)b&&B in b||null==y[B]||w(n,B,y[B],y[B]=void 0,J);if(b)for(var v in b)"children"===v||"innerHTML"===v||v in y&&b[v]===("value"===v||"checked"===v?n[v]:y[v])||w(n,v,y[v],y[v]=b[v],J);if(!S&&t&&1===t.length&&"string"==typeof t[0]&&m&&m instanceof Text&&!m.nextSibling)m.nodeValue!=t[0]&&(m.nodeValue=t[0]);else if(t&&
t.length||m){B=f;var r,I,u;v=B.childNodes;b=[];var m={},y=n=0,Z=v.length,x=0,M=t&&t.length;if(Z)for(l=0;l<Z;l++)if(I=v[l],u=I[F],r=M?(p=I.f)?p.X:u?u.key:null:null,null!=r)n++,m[r]=I;else if(S||u)b[x++]=I;if(M)for(l=0;l<M;l++){I=t[l];u=null;r=I.key;if(null!=r)n&&r in m&&(u=m[r],m[r]=void 0,n--);else if(!u&&y<x)for(r=y;r<x;r++){var p=b[r],C;if(C=p){C=p;var D=I;C=k(D)?C instanceof Text:k(D.nodeName)?!C.A&&q(C,D.nodeName):h(D.nodeName)?(C.A?C.A===D.nodeName:!0)||E(D):void 0}if(C){u=p;b[r]=void 0;r===
x-1&&x--;r===y&&y++;break}}(u=P(u,I,d,e))&&u!==B&&(l>=Z?B.appendChild(u):u!==v[l]&&(u===v[l+1]&&A(v[l]),B.insertBefore(u,v[l]||null)))}if(n)for(l in m)m[l]&&N(m[l]);for(;y<=x;)(u=b[x--])&&N(u)}c&&"function"==typeof c.m&&(a.m=c.m)(f);J=g;return f}function N(a,d){var e=a.f;if(e)U(e,!d);else for(a[F]&&a[F].m&&a[F].m(null),d||(A(a),a instanceof Element&&(a.f=a.A=null,e=a.ka||b(a.nodeName),(R[e]||(R[e]=[])).push(a)));e=a.lastChild;)N(e,d)}function ha(a,b,d){var e=new a(b,d),c=aa[a.name];ba.call(e,b,d);
if(c)for(b=c.length;b--;)if(c[b].constructor===a){e.l=c[b].l;c.splice(b,1);break}return e}function T(a,b,d,e,c){a.L||(a.L=!0,(a.I=b.m)&&delete b.m,(a.X=b.key)&&delete b.key,!a.h||c?a.va&&a.va():a.wa&&a.wa(b,e),e&&e!==a.context&&(a.P||(a.P=a.context),a.context=e),a.R||(a.R=a.v),a.v=b,a.L=!1,0!==d&&(1!==d&&!1===x.jb&&a.h?n(a):C(a,1,c)),a.I&&a.I(a))}function C(a,b,d,e){if(!a.L){var c,f,l,k,m=a.v,n=a.state,p=a.context,q=a.R||m,P=a.S||n,A=a.P||p,v=a.h;k=a.l;var r=v||k,B=a.f;v&&(a.v=q,a.state=P,a.context=
A,2!==b&&a.La&&!1===a.La(m,n,p)?c=!0:a.ya&&a.ya(m,n,p),a.v=m,a.state=n,a.context=p);a.R=a.S=a.P=a.l=null;a.K=!1;if(!c){a.g&&(f=a.g(m,n,p));for(a.Ca&&(p=g(g({},p),a.Ca()));E(f);)f=H(f,p);var u,w,m=f&&f.nodeName;if(h(m))w=z(f),(l=B)&&l.constructor===m&&w.key==l.X?T(l,w,1,p):(u=l,l=ha(m,w,p),l.l=l.l||k,l.aa=a,a.f=l,T(l,w,0,p),C(l,1,d,!0)),w=l.h;else{k=r;if(u=B)k=a.f=null;if(r||1===b)k&&(k.f=null),w=y(k,f,p,d||!v,r&&r.parentNode,!0)}r&&w!==r&&l!==B&&(l=r.parentNode)&&w!==l&&(l.replaceChild(w,r),u||(r.f=
null,N(r)));u&&U(u,w!==r);if((a.h=w)&&!e){for(u=r=a;u=u.aa;)(r=u).h=w;w.f=r;w.A=r.constructor}}!v||d?ga.unshift(a):c||(a.ua&&a.ua(q,P,A),x.pa&&x.pa(a));if(c=a.ba)for(;d=c.pop();)d.call(a);Y||e||t()}}function U(a,b){x.sa&&x.sa(a);var d=a.h;a.L=!0;a.xa&&a.xa();a.h=null;var e=a.f;if(e)U(e,b);else if(d){d[F]&&d[F].m&&d[F].m(null);a.l=d;if(b){A(d);var e=a.constructor.name,c=aa[e];c?c.push(a):aa[e]=[a]}for(;e=d.lastChild;)N(e,!b)}a.I&&a.I(null);a.ta&&a.ta()}function ba(a,b){this.K=!0;this.context=b;this.v=
a;this.state||(this.state={})}var x={},D=[],ea={},ia="undefined"!=typeof Promise&&Promise.resolve(),na=ia?function(a){ia.then(a)}:setTimeout,oa={};K();K();var F="undefined"!=typeof Symbol?Symbol.for("preactattr"):"__preactattr_",pa={Ra:1,Sa:1,Va:1,Za:1,flex:1,flexGrow:1,ab:1,flexShrink:1,$a:1,fontWeight:1,cb:1,lineHeight:1,opacity:1,order:1,orphans:1,ib:1,widows:1,zIndex:1,zoom:1},fa={blur:1,error:1,focus:1,load:1,resize:1,scroll:1},X=[],R={},ga=[],Y=0,J=!1,S=!1,aa={};g(ba.prototype,{eb:function(a,
b){var d=this.na||(this.na={});return d[a+b]||(d[a+b]=l(this,a,b))},G:function(a,b){var d=this.state;this.S||(this.S=g({},d));g(d,h(a)?a(d,this.v):a);b&&(this.ba=this.ba||[]).push(b);n(this)},bb:function(){C(this,2)},g:function(){}});a.b=f;a.Ua=function(a,b){return f(a.nodeName,g(g({},a.attributes),b),2<arguments.length?[].slice.call(arguments,2):a.children)};a.w=ba;a.g=function(a,b,d){return y(d,a,{},!1,b)};a.hb=m;a.options=x})},function(c,b,a){var d=a(12);c.a=function(a){return function g(b){return 0===
arguments.length||d(b)?g:a.apply(this,arguments)}}},function(c,b,a){var d=a(3),e=a(7),f=a(58);c.a=function(){var a=!{toString:null}.propertyIsEnumerable("toString"),b="constructor valueOf isPrototypeOf toString propertyIsEnumerable hasOwnProperty toLocaleString".split(" "),c=function(){return arguments.propertyIsEnumerable("length")}();return"function"!==typeof Object.keys||c?d(function(d){if(Object(d)!==d)return[];var g,h,l=[];h=c&&f(d);for(g in d)!e(g,d)||h&&"length"===g||(l[l.length]=g);if(a)for(h=
b.length-1;0<=h;){g=b[h];var k;if(k=e(g,d)){a:{for(k=0;k<l.length;){if(l[k]===g){k=!0;break a}k+=1}k=!1}k=!k}k&&(l[l.length]=g);--h}return l}):d(function(a){return Object(a)!==a?[]:Object.keys(a)})}()},function(c){c.a=function a(d,e,c){switch(arguments.length){case 1:return a(d,0,d.length);case 2:return a(d,e,d.length);default:for(var f=[],h=0,k=Math.max(0,Math.min(d.length,c)-e);h<k;)f[h]=d[e+h],h+=1;return f}}},function(c,b,a){var d=a(18),e=a(61),f=a(5);c.a=function(a,b,c){return function(){var g=
arguments.length;if(0===g)return c();var h=arguments[g-1];if(!d(h)){g=f(arguments,0,g-1);if("function"===typeof h[a])return h[a].apply(h,g);if(e(h))return b.apply(null,g)(h)}return c.apply(this,arguments)}}},function(c){c.a=function(b,a){return Object.prototype.hasOwnProperty.call(a,b)}},function(c,b,a){var d=a(71),e=a(44),f=a(72);c.a=function(){function a(a,b,d){for(var e=d.next();!e.done;){if((b=a["@@transducer/step"](b,e.value))&&b["@@transducer/reduced"]){b=b["@@transducer/value"];break}e=d.next()}return a["@@transducer/result"](b)}
K();K();L();var b="undefined"!==typeof Symbol?Symbol.iterator:"@@iterator";return function(c,g,h){"function"===typeof c&&(c=d(c));if(f(h)){for(var k=0,l=h.length;k<l;){if((g=c["@@transducer/step"](g,h[k]))&&g["@@transducer/reduced"]){g=g["@@transducer/value"];break}k+=1}return c["@@transducer/result"](g)}if("function"===typeof h.reduce)return c["@@transducer/result"](h.reduce(e(c["@@transducer/step"],c),g));if(null!=h[b])return a(c,g,h[b]());if("function"===typeof h.next)return a(c,g,h);throw new TypeError("reduce: list must be array or iterable");
}}()},function(c){c.a={D:function(){return this.c["@@transducer/init"]()},result:function(b){return this.c["@@transducer/result"](b)}}},function(c,b,a){a(88);c.a=self.fetch.bind(self)},function(c){c.a=function(b,a){switch(b){case 0:return function(){return a.apply(this,arguments)};case 1:return function(b){return a.apply(this,arguments)};case 2:return function(b,c){return a.apply(this,arguments)};case 3:return function(b,c,f){return a.apply(this,arguments)};case 4:return function(b,c,f,g){return a.apply(this,
arguments)};case 5:return function(b,c,f,g,h){return a.apply(this,arguments)};case 6:return function(b,c,f,g,h,k){return a.apply(this,arguments)};case 7:return function(b,c,f,g,h,k,l){return a.apply(this,arguments)};case 8:return function(b,c,f,g,h,k,l,n){return a.apply(this,arguments)};case 9:return function(b,c,f,g,h,k,l,n,m){return a.apply(this,arguments)};case 10:return function(b,c,f,g,h,k,l,n,m,E){return a.apply(this,arguments)};default:throw Error("First argument to _arity must be a non-negative integer no greater than ten");
}}},function(c){c.a=function(b){return null!=b&&"object"===typeof b&&!0===b["@@functional/placeholder"]}},function(c,b,a){var d=a(2).b;c.a=function(a){var b=a.style;return d("svg",{className:"icon"+(b?" icon--"+b:"")},d("use",{xlinkHref:"images/icons.svg#icon-"+a.name}))}},function(c,b,a){var d=a(76),e=a(20);c.a=function(){if(0===arguments.length)throw Error("compose requires at least one argument");return d.apply(this,e(arguments))}},function(c,b,a){var d=a(11),e=a(3);b=a(1);var f=a(17);c.a=b(function(a,
b){return 1===a?e(b):d(a,f(a,[],b))})},function(c,b,a){var d=a(18),e=a(5);c.a=function(a,b){return function(){var c=arguments.length;if(0===c)return b();var f=arguments[c-1];return d(f)||"function"!==typeof f[a]?b.apply(this,arguments):f[a].apply(f,e(arguments,0,c-1))}}},function(c,b,a){var d=a(11),e=a(12);c.a=function g(a,b,c){return function(){for(var h=[],m=0,k=a,l=0;l<b.length||m<arguments.length;){var q;l<b.length&&(!e(b[l])||m>=arguments.length)?q=b[l]:(q=arguments[m],m+=1);h[l]=q;e(q)||--k;
l+=1}return 0>=k?c.apply(this,h):d(k,g(a,h,c))}}},function(c){c.a=Array.isArray||function(b){return null!=b&&0<=b.length&&"[object Array]"===Object.prototype.toString.call(b)}},function(c,b,a){b=a(1);var d=a(59),e=a(5),f=a(15),g=a(85);c.a=b(function(a,b){return f(a+1,function(){var c=arguments[a];if(null!=c&&d(c[b]))return c[b].apply(c,e(arguments,0,a));throw new TypeError(g(c)+' does not have a method named "'+b+'"');})})},function(c,b,a){b=a(3);var d=a(24),e=a(5);c.a=b(function(a){return d(a)?a.split("").reverse().join(""):
e(a).reverse()})},function(c,b,a){b=a(3);var d=a(15);c.a=b(function(a){return d(a.length,a)})},function(c,b,a){var d=a(57);c.a=function(a,b){return 0<=d(b,a,0)}},function(c,b,a){var d=a(3),e=a(1),f=a(12);c.a=function(a){return function k(b,c,g){switch(arguments.length){case 0:return k;case 1:return f(b)?k:e(function(c,d){return a(b,c,d)});case 2:return f(b)&&f(c)?k:f(b)?e(function(b,d){return a(b,c,d)}):f(c)?e(function(c,d){return a(b,c,d)}):d(function(d){return a(b,c,d)});default:return f(b)&&f(c)&&
f(g)?k:f(b)&&f(c)?e(function(b,c){return a(b,c,g)}):f(b)&&f(g)?e(function(b,d){return a(b,c,d)}):f(c)&&f(g)?e(function(c,d){return a(b,c,d)}):f(b)?d(function(b){return a(b,c,g)}):f(c)?d(function(c){return a(b,c,g)}):f(g)?d(function(d){return a(b,c,d)}):a(b,c,g)}}}},function(c){c.a=function(b){return"[object String]"===Object.prototype.toString.call(b)}},function(c){c.a=function(b,a){for(var c=0,e=a.length,f=Array(e);c<e;)f[c]=b(a[c]),c+=1;return f}},function(c){c.a=function(b){return b&&b["@@transducer/reduced"]?
b:{"@@transducer/value":b,"@@transducer/reduced":!0}}},function(c,b,a){b=a(1);var d=a(6),e=a(25),f=a(8),g=a(68),h=a(15),k=a(4);c.a=b(d("map",g,function(a,b){switch(Object.prototype.toString.call(b)){case "[object Function]":return h(b.length,function(){return a.call(this,b.apply(this,arguments))});case "[object Object]":return f(function(c,d){c[d]=a(b[d]);return c},{},k(b));default:return e(a,b)}}))},function(c,b,a){b=a(1);c.a=b(function(a,b){return b[a]})},function(c,b,a){b=a(16);a=a(23);c.a=a(b("slice",
function(a,b,c){return Array.prototype.slice.call(c,a,b)}))},function(c,b,a){function d(a){var b=O(a.split("-"));a=b.next().value;b=b.next().value;return f[b]+" "+a}var e=a(2).b,f={"01":"January","02":"February","03":"March","04":"April","05":"May","06":"June","07":"July","08":"August","09":"September",10:"October",11:"November",12:"December"};c.a=function(a){var b=e("div",{className:"col-xs-12 col-sm-3 text-xs-center pb-1"},e("a",{href:a.url},e("img",{className:"img-fluid center-block",src:a.image}))),
c=e("h4",null,a.role," at ",e("a",{href:a.url},a.name)),f=d(a.startDate),g;g=(g=a.endDate)?d(g):"Present";return e("div",{className:"row pb-1"},b,e("div",{className:"col-xs-12 col-sm-9"},c,f," \u2014 ",g,e("div",{dangerouslySetInnerHTML:{ma:"<p>"+a.description.split("\n\n").join("</p><p>")+"</p>"}})))}},function(c,b,a){function d(a){g.call(this,a);this.state={items:a.data?this.ea(a.data):""}}var e=Object.assign||function(a){for(var b=1;b<arguments.length;b++){var c=arguments[b],d;for(d in c)Object.prototype.hasOwnProperty.call(c,
d)&&(a[d]=c[d])}return a};b=a(2);var f=b.b,g=b.w,h=a(10),k=a(30);V(d,g);d.prototype.B=function(){var a=this;h("data/experience.json").then(function(a){return a.json()}).then(function(b){return a.ea(b)}).then(function(b){return a.G({items:b})})};d.prototype.ea=function(a){return a.results.map(function(a){return f(k,e({key:a.name},a))})};d.prototype.g=function(){return f("div",{id:"experience",className:"section"},f("h2",{className:"display-4 mb-2 text-xs-center"},"Experience"),this.state.items)};c.a=
d},function(c,b,a){var d=a(2).b;c.a=function(){return d("footer",{className:"section hidden-print"},d("div",{className:"row"},d("div",{className:"col-xs-12"},"Made with \u2764 by Joseph Wynn. The code for this page is ",d("a",{href:"https://github.com/wildlyinaccurate/resume"},"available on GitHub"),".")))}},function(c,b,a){function d(a){var b="#"+f(a);return e("li",{key:a,className:"nav-item"},e("a",{href:b,className:"nav-link"},a))}var e=a(2).b,f=a(43),g=a(13);c.a=function(){return e("nav",{className:"navbar navbar-fixed-top bg-faded"},
e("div",{className:"container"},e("div",{className:"row"},e("div",{id:"navbar",className:"col-xs-12 col-sm-7 col-md-8 col-lg-9"},e("h2",{className:"float-sm-left mr-2 text-xs-center"},"Joseph Wynn"),e("ul",{className:"nav nav-pills hidden-md-down"},["Toolkit","Experience","Publications","Open Source"].map(d))),e("div",{className:"header-links hidden-xs-down col-sm-5 col-md-4 col-lg-3 text-xs-right"},e("a",{className:"header-link",href:"https://wildlyinaccurate.com/"},e(g,{name:"wildlyinaccurate",
style:"super"}),e("span",{className:"header-link__text"},"wildlyinaccurate.com")),e("a",{className:"header-link",href:"https://github.com/wildlyinaccurate"},e(g,{name:"github",style:"super"}),e("span",{className:"header-link__text"},"wildlyinaccurate")),e("a",{className:"header-link",href:"https://twitter.com/Joseph_Wynn"},e(g,{name:"twitter",style:"super"}),e("span",{className:"header-link__text"},"@Joseph_Wynn"))))))}},function(c,b,a){var d=a(2).b;c.a=function(){return d("div",{id:"introduction",
className:"introduction section text-xs-center"},d("h4",{className:"introduction__heading display-2"},"Hello!"),d("p",{className:"lead"},"I'm a web developer for BBC News. I want to build web sites for ",d("a",{href:"https://www.youtube.com/watch?v=E6hGubMkNfM"},"the next billion"),", so unsurprisingly I have a passion for performance and accessibility. Most days you can find me writing JavaScript, Ruby, and Shell. When I'm not building for the web, I'm trying to improve workflows by creating tooling and optimising build pipelines."),
d("p",{className:"lead"},"In my spare time I maintain several open source projects, and I like to write Haskell and Elm. Outside of programming I am a cook, runner, rock climber and guitarist. I'm also an ",d("a",{href:"https://wildlyinaccurate.com/accidental-keyboard-enthusiasm/"},"accidental keyboard enthusiast"),". I sometimes blog at ",d("a",{href:"https://wildlyinaccurate.com/"},"Wildly Inaccurate"),"."))}},function(c,b,a){var d=a(2).b,e=a(13);c.a=function(a){return d("div",{className:"col-xs-12 col-lg-6 mb-2"},
d("h4",null,d("small",{title:a.stargazers_count+" stars",className:"star-count float-xs-right"},a.stargazers_count,d(e,{name:"star"})),d("a",{href:a.html_url},a.name),d("span",{className:"tag tag-primary ml-1/2"},a.language)),d("p",null,a.description))}},function(c,b,a){function d(a){g.call(this,a);this.state={items:""}}var e=Object.assign||function(a){for(var b=1;b<arguments.length;b++){var c=arguments[b],d;for(d in c)Object.prototype.hasOwnProperty.call(c,d)&&(a[d]=c[d])}return a};b=a(2);var f=
b.b,g=b.w,h=a(27);b=a(20);var k=a(83),l=a(42),n=a(35),m=b("ff7cece3c58d2a457908136b35475cbdf708d3d6");V(d,g);d.prototype.B=function(){var a=this;l.fetch(m).then(l.sort("stargazers_count")).then(k(12)).then(this.Ea).then(this.za).then(function(b){return a.G({items:b})})};d.prototype.Ea=function(a){return Promise.all(h(l.Da,a))};d.prototype.za=function(a){return a.map(function(a){return f(n,e({key:a.name},a))})};d.prototype.g=function(){return f("div",{id:"open-source",className:"section hidden-print"},
f("h2",{className:"display-4 mb-2 text-xs-center"},"Open Source"),f("p",{className:"text-xs-center"},"Below is a collection of my most popular open source work. You can visit ",f("a",{href:"https://github.com/wildlyinaccurate?tab=repositories"},"my GitHub profile")," for a more complete picture of the open source work that I do."),f("div",{className:"row"},this.state.items))};c.a=d},function(c,b,a){var d=a(2).b;c.a=function(){return d("div",{className:"visible-print-block container-fluid text-xs-right"},
d("address",null,d("strong",null,"Joseph Wynn"),d("br",null),"+44 77 1740 1436",d("br",null),"joseph@wildlyinaccurate.com",d("br",null),"https://resume.wildlyinaccurate.com"))}},function(c,b,a){function d(a){f.call(this,a);this.state={T:a.data?this.fa(a.data):""}}b=a(2);var e=b.b,f=b.w,g=a(10);V(d,f);d.prototype.B=function(){var a=this;g("data/publications.json").then(function(a){return a.json()}).then(function(b){return a.fa(b)}).then(function(b){a.G({T:b})})};d.prototype.fa=function(a){var b=this;
return a.results.map(function(a){return e("div",{key:a.title,className:"col-sm-6"},e("h3",null,a.title," (",a.year,")"),e("p",null,a.summary),e("p",null,b.Ga(a.links)))})};d.prototype.Ga=function(a){return a.map(function(a){return e("a",{key:a.title,className:"tag tag-success mr-1/2",href:a.url},a.title)})};d.prototype.g=function(){return e("div",{id:"publications",className:"section"},e("h2",{className:"display-4 mb-2 text-xs-center"},"Publications"),e("div",{className:"row"},this.state.T))};c.a=
d},function(c,b,a){var d=a(2).b,e=a(13);c.a=function(a){return d("h5",null,d(e,{name:a.icon})," ",a.name)}},function(c,b,a){function d(a){g.call(this,a);this.state={W:a.data?this.ga(a.data):""}}var e=Object.assign||function(a){for(var b=1;b<arguments.length;b++){var c=arguments[b],d;for(d in c)Object.prototype.hasOwnProperty.call(c,d)&&(a[d]=c[d])}return a};b=a(2);var f=b.b,g=b.w,h=a(10),k=a(14),l=a(50),n=a(27);b=a(74);var m=a(28),E=a(87),H=a(39),q=b(function(a,b){a=n(function(a){return f(H,e({key:a.name},
a))},a);return f("div",{key:b,className:"col-xs-6 col-md-4 mb-3"},f("h3",null,b),a)});V(d,g);d.prototype.B=function(){var a=this;h("data/skills.json").then(function(a){return a.json()}).then(function(b){return a.ga(b)}).then(function(b){a.G({W:b})})};d.prototype.ga=function(a){return k(E,q,l(m("category")),m("results"))(a)};d.prototype.g=function(){return f("div",{id:"toolkit",className:"section text-xs-center"},f("h2",{className:"display-4 mb-2"},"Toolkit"),f("div",{className:"row center-cols"},
this.state.W))};c.a=d},function(c,b,a){function d(a){f.apply(this,arguments)}b=a(2);var e=b.b,f=b.w,g=a(33),h=a(37),k=a(32),l=a(34),n=a(31),m=a(40),E=a(38),H=a(36);V(d,f);d.prototype.g=function(){var a=this.v.data||{};return e("div",null,e(h,null),e("div",{className:"container mt-2"},e(g,null),e(l,null),e(m,{data:a.W}),e(n,{data:a.Ya}),e(E,{data:a.T}),e(H,null),e(k,null)))};c.a=d},function(c,b,a){function d(a){return e(a.languages_url).then(function(a){return a.json()}).then(l).then(h(q))}var e=a(10),
f=a(14);b=a(45);var g=a(21),h=a(48),k=a(49),l=a(4),n=a(75),m=a(28),E=a(20),H=a(80);c.a.fetch=function(a){return e("https://api.github.com/user/repos?per_page=100&access_token="+a).then(function(a){return a.json()})};c.a.sort=g(function(a,b){return f(E,H(m(a)))(b)});var q=f(n,k(b)(["HTML","CSS"]));c.a.Da=function(a){return q(a.language)?Promise.resolve(a):d(a).then(function(b){a.language=b;return a})}},function(c,b,a){b=a(14);var d=a(73),e=a(81);a=a(84);a=b(d("-"),e(" "),a);c.a=a},function(c,b,a){var d=
a(11);b=a(1);c.a=b(function(a,b){return d(a.length,function(){return a.apply(b,arguments)})})},function(c,b,a){b=a(22);a=a(1);c.a=a(b)},function(c,b,a){b=a(1);var d=a(54);c.a=b(function(a,b){return d(a,b,[],[])})},function(c,b,a){b=a(1);var d=a(6),e=a(55),f=a(60),g=a(8),h=a(66),k=a(4);c.a=b(d("filter",h,function(a,b){return f(b)?g(function(c,d){a(b[d])&&(c[d]=b[d]);return c},{},k(b)):e(a,b)}))},function(c,b,a){b=a(1);var d=a(6);a=a(67);c.a=b(d("find",a,function(a,b){for(var c=0,d=b.length;c<d;){if(a(b[c]))return b[c];
c+=1}}))},function(c,b,a){b=a(3);var d=a(5),e=a(21);c.a=b(function(a){return e(function(b,c){var e=d(arguments);e[0]=c;e[1]=b;return a.apply(this,e)})})},function(c,b,a){b=a(16);var d=a(1);a=a(78);c.a=d(b("groupBy",a(function(a,b){null==a&&(a=[]);a.push(b);return a},null)))},function(c,b,a){b=a(1);c.a=b(function(a,b){return a===b?0!==a||1/a===1/b:a!==a&&b!==b})},function(c){c.a=function(b){for(var a=[],c;!(c=b.next()).done;)a.push(c.value);return a}},function(c){c.a=function(b){return function(){return!b.apply(this,
arguments)}}},function(c,b,a){var d=a(52),e=a(56),f=a(7),g=a(51),h=a(4),k=a(86);c.a=function n(a,b,c,q){if(g(a,b))return!0;if(k(a)!==k(b)||null==a||null==b)return!1;if("function"===typeof a.C||"function"===typeof b.C)return"function"===typeof a.C&&a.C(b)&&"function"===typeof b.C&&b.C(a);switch(k(a)){case "Arguments":case "Array":case "Object":if("function"===typeof a.constructor&&"Promise"===e(a.constructor))return a===b;break;case "Boolean":case "Number":case "String":if(typeof a!==typeof b||!g(a.valueOf(),
b.valueOf()))return!1;break;case "Date":if(!g(a.valueOf(),b.valueOf()))return!1;break;case "Error":return a.name===b.name&&a.message===b.message;case "RegExp":if(a.source!==b.source||a.global!==b.global||a.ignoreCase!==b.ignoreCase||a.multiline!==b.multiline||a.Ma!==b.Ma||a.Na!==b.Na)return!1;break;case "Map":case "Set":if(!n(d(a.entries()),d(b.entries()),c,q))return!1;break;case "Int8Array":case "Uint8Array":case "Uint8ClampedArray":case "Int16Array":case "Uint16Array":case "Int32Array":case "Uint32Array":case "Float32Array":case "Float64Array":break;
case "ArrayBuffer":break;default:return!1}var m=h(a);if(m.length!==h(b).length)return!1;for(var A=c.length-1;0<=A;){if(c[A]===a)return q[A]===b;--A}c.push(a);q.push(b);for(A=m.length-1;0<=A;){var w=m[A];if(!f(w,b)||!n(b[w],a[w],c,q))return!1;--A}c.pop();q.pop();return!0}},function(c){c.a=function(b,a){for(var c=0,e=a.length,f=[];c<e;)b(a[c])&&(f[f.length]=a[c]),c+=1;return f}},function(c){c.a=function(b){b=String(b).match(/^function (\w*)/);return null==b?"":b[1]}},function(c,b,a){var d=a(46);c.a=
function(a,b,c){var e;if("function"===typeof a.indexOf)switch(typeof b){case "number":if(0===b){for(b=1/b;c<a.length;){e=a[c];if(0===e&&1/e===b)return c;c+=1}return-1}if(b!==b){for(;c<a.length;){e=a[c];if("number"===typeof e&&e!==e)return c;c+=1}return-1}return a.indexOf(b,c);case "string":case "boolean":case "function":case "undefined":return a.indexOf(b,c);case "object":if(null===b)return a.indexOf(b,c)}for(;c<a.length;){if(d(a[c],b))return c;c+=1}return-1}},function(c,b,a){var d=a(7);c.a=function(){var a=
Object.prototype.toString;return"[object Arguments]"===a.call(arguments)?function(b){return"[object Arguments]"===a.call(b)}:function(a){return d("callee",a)}}()},function(c){c.a=function(b){return"[object Function]"===Object.prototype.toString.call(b)}},function(c){c.a=function(b){return"[object Object]"===Object.prototype.toString.call(b)}},function(c){c.a=function(b){return"function"===typeof b["@@transducer/step"]}},function(c){c.a=function(b,a){return function(){return a.call(this,b.apply(this,
arguments))}}},function(c){c.a=function(b){return'"'+b.replace(/\\/g,"\\\\").replace(/[\b]/g,"\\b").replace(/\f/g,"\\f").replace(/\n/g,"\\n").replace(/\r/g,"\\r").replace(/\t/g,"\\t").replace(/\v/g,"\\v").replace(/\0/g,"\\0").replace(/"/g,'\\"')+'"'}},function(c){c.a=function(){function b(a){return(10>a?"0":"")+a}return"function"===typeof Date.prototype.toISOString?function(a){return a.toISOString()}:function(a){return a.getUTCFullYear()+"-"+b(a.getUTCMonth()+1)+"-"+b(a.getUTCDate())+"T"+b(a.getUTCHours())+
":"+b(a.getUTCMinutes())+":"+b(a.getUTCSeconds())+"."+(a.getUTCMilliseconds()/1E3).toFixed(3).slice(2,5)+"Z"}}()},function(c,b,a){var d=a(22),e=a(25),f=a(63),g=a(64),h=a(4),k=a(79);c.a=function n(a,b){function c(a,b){return e(function(b){return f(b)+": "+m(a[b])},b.slice().sort())}function m(c){var e=b.concat([a]);return d(c,e)?"<Circular>":n(c,e)}switch(Object.prototype.toString.call(a)){case "[object Arguments]":return"(function() { return arguments; }("+e(m,a).join(", ")+"))";case "[object Array]":return"["+
e(m,a).concat(c(a,k(function(a){return/^\d+$/.test(a)},h(a)))).join(", ")+"]";case "[object Boolean]":return"object"===typeof a?"new Boolean("+m(a.valueOf())+")":a.toString();case "[object Date]":return"new Date("+(isNaN(a.valueOf())?m(NaN):f(g(a)))+")";case "[object Null]":return"null";case "[object Number]":return"object"===typeof a?"new Number("+m(a.valueOf())+")":-Infinity===1/a?"-0":a.toString(10);case "[object String]":return"object"===typeof a?"new String("+m(a.valueOf())+")":f(a);case "[object Undefined]":return"undefined";
default:if("function"===typeof a.toString){var z=a.toString();if("[object Object]"!==z)return z}return"{"+c(a,h(a)).join(", ")+"}"}}},function(c,b,a){var d=a(1),e=a(9);c.a=function(){function a(a,b){this.c=b;this.u=a}a.prototype["@@transducer/init"]=e.D;a.prototype["@@transducer/result"]=e.result;a.prototype["@@transducer/step"]=function(a,b){return this.u(b)?this.c["@@transducer/step"](a,b):a};return d(function(b,c){return new a(b,c)})}()},function(c,b,a){var d=a(1),e=a(26),f=a(9);c.a=function(){function a(a,
b){this.c=b;this.u=a;this.ha=!1}a.prototype["@@transducer/init"]=f.D;a.prototype["@@transducer/result"]=function(a){this.ha||(a=this.c["@@transducer/step"](a,void 0));return this.c["@@transducer/result"](a)};a.prototype["@@transducer/step"]=function(a,b){this.u(b)&&(this.ha=!0,a=e(this.c["@@transducer/step"](a,b)));return a};return d(function(b,c){return new a(b,c)})}()},function(c,b,a){var d=a(1),e=a(9);c.a=function(){function a(a,b){this.c=b;this.u=a}a.prototype["@@transducer/init"]=e.D;a.prototype["@@transducer/result"]=
e.result;a.prototype["@@transducer/step"]=function(a,b){return this.c["@@transducer/step"](a,this.u(b))};return d(function(b,c){return new a(b,c)})}()},function(c,b,a){var d=a(17),e=a(7),f=a(9);c.a=function(){function a(a,b,c,d){this.Pa=a;this.Oa=b;this.Fa=c;this.c=d;this.inputs={}}a.prototype["@@transducer/init"]=f.D;a.prototype["@@transducer/result"]=function(a){for(var b in this.inputs)if(e(b,this.inputs)&&(a=this.c["@@transducer/step"](a,this.inputs[b]),a["@@transducer/reduced"])){a=a["@@transducer/value"];
break}this.inputs=null;return this.c["@@transducer/result"](a)};a.prototype["@@transducer/step"]=function(a,b){var c=this.Fa(b);this.inputs[c]=this.inputs[c]||[c,this.Oa];this.inputs[c][1]=this.Pa(this.inputs[c][1],b);return a};return d(4,[],function(b,c,d,e){return new a(b,c,d,e)})}()},function(c,b,a){var d=a(1),e=a(26),f=a(9);c.a=function(){function a(a,b){this.c=b;this.n=a;this.O=0}a.prototype["@@transducer/init"]=f.D;a.prototype["@@transducer/result"]=f.result;a.prototype["@@transducer/step"]=
function(a,b){this.O+=1;a=0===this.n?a:this.c["@@transducer/step"](a,b);return this.O>=this.n?e(a):a};return d(function(b,c){return new a(b,c)})}()},function(c){c.a=function(){function b(a){this.u=a}b.prototype["@@transducer/init"]=function(){throw Error("init not implemented on XWrap");};b.prototype["@@transducer/result"]=function(a){return a};b.prototype["@@transducer/step"]=function(a,b){return this.u(a,b)};return function(a){return new b(a)}}()},function(c,b,a){b=a(3);var d=a(18),e=a(24);c.a=
b(function(a){return d(a)?!0:!a||"object"!==typeof a||e(a)?!1:1===a.nodeType?!!a.length:0===a.length?!0:0<a.length?a.hasOwnProperty(0)&&a.hasOwnProperty(a.length-1):!1})},function(c,b,a){b=a(19);c.a=b(1,"join")},function(c,b,a){b=a(1);var d=a(8),e=a(4);c.a=b(function(a,b){return d(function(c,d){c[d]=a(b[d],d,b);return c},{},e(b))})},function(c,b,a){b=a(3);c.a=b(function(a){return!a})},function(c,b,a){var d=a(11),e=a(62),f=a(77),g=a(82);c.a=function(){if(0===arguments.length)throw Error("pipe requires at least one argument");
return d(arguments[0].length,f(e,arguments[0],g(arguments)))}},function(c,b,a){b=a(23);a=a(8);c.a=b(a)},function(c,b,a){b=a(17);var d=a(6),e=a(7),f=a(8);a=a(69);c.a=b(4,[],d("reduceBy",a,function(a,b,c,d){return f(function(d,f){var g=c(f);d[g]=a(e(g,d)?d[g]:b,f);return d},{},d)}))},function(c,b,a){var d=a(53);b=a(1);var e=a(47);c.a=b(function(a,b){return e(d(a),b)})},function(c,b,a){b=a(1);var d=a(5);c.a=b(function(a,b){return d(b).sort(function(b,c){b=a(b);c=a(c);return b<c?-1:b>c?1:0})})},function(c,
b,a){b=a(19);c.a=b(1,"split")},function(c,b,a){b=a(16);a=a(29);c.a=b("tail",a(1,Infinity))},function(c,b,a){b=a(1);var d=a(6),e=a(70),f=a(29);c.a=b(d("take",e,function(a,b){return f(0,0>a?Infinity:a,b)}))},function(c,b,a){b=a(19);c.a=b(0,"toLowerCase")},function(c,b,a){b=a(3);var d=a(65);c.a=b(function(a){return d(a,[])})},function(c,b,a){b=a(3);c.a=b(function(a){return null===a?"Null":void 0===a?"Undefined":Object.prototype.toString.call(a).slice(8,-1)})},function(c,b,a){b=a(3);var d=a(4);c.a=b(function(a){for(var b=
d(a),c=b.length,e=[],k=0;k<c;)e[k]=a[b[k]],k+=1;return e})},function(){(function(c){function b(a){"string"!==typeof a&&(a=String(a));if(/[^a-z0-9\-#$%&'*+.\^_`|~]/i.test(a))throw new TypeError("Invalid character in header field name");return a.toLowerCase()}function a(a){"string"!==typeof a&&(a=String(a));return a}function d(a){var b={next:function(){var b=a.shift();return{done:void 0===b,value:b}}};z.ja&&(K(),L(),b[Symbol.iterator]=function(){return b});return b}function e(a){this.map={};a instanceof
e?a.forEach(function(a,b){this.append(b,a)},this):a&&Object.getOwnPropertyNames(a).forEach(function(b){this.append(b,a[b])},this)}function f(a){if(a.bodyUsed)return Promise.reject(new TypeError("Already read"));a.bodyUsed=!0}function g(a){return new Promise(function(b,c){a.onload=function(){b(a.result)};a.onerror=function(){c(a.error)}})}function h(a){var b=new FileReader,c=g(b);b.readAsArrayBuffer(a);return c}function k(a){a=new Uint8Array(a);for(var b=Array(a.length),c=0;c<a.length;c++)b[c]=String.fromCharCode(a[c]);
return b.join("")}function l(a){if(a.slice)return a.slice(0);var b=new Uint8Array(a.byteLength);b.set(new Uint8Array(a));return b.buffer}function n(){this.bodyUsed=!1;this.Z=function(a){if(this.s=a)if("string"===typeof a)this.J=a;else if(z.blob&&Blob.prototype.isPrototypeOf(a))this.o=a;else if(z.formData&&FormData.prototype.isPrototypeOf(a))this.Y=a;else if(z.searchParams&&URLSearchParams.prototype.isPrototypeOf(a))this.J=a.toString();else if(z.arrayBuffer&&z.blob&&a&&DataView.prototype.isPrototypeOf(a))this.i=
l(a.buffer),this.s=new Blob([this.i]);else if(z.arrayBuffer&&(ArrayBuffer.prototype.isPrototypeOf(a)||w(a)))this.i=l(a);else throw Error("unsupported BodyInit type");else this.J="";this.headers.get("content-type")||("string"===typeof a?this.headers.set("content-type","text/plain;charset=UTF-8"):this.o&&this.o.type?this.headers.set("content-type",this.o.type):z.searchParams&&URLSearchParams.prototype.isPrototypeOf(a)&&this.headers.set("content-type","application/x-www-form-urlencoded;charset=UTF-8"))};
z.blob&&(this.blob=function(){var a=f(this);if(a)return a;if(this.o)return Promise.resolve(this.o);if(this.i)return Promise.resolve(new Blob([this.i]));if(this.Y)throw Error("could not read FormData body as blob");return Promise.resolve(new Blob([this.J]))},this.arrayBuffer=function(){return this.i?f(this)||Promise.resolve(this.i):this.blob().then(h)});this.text=function(){var a=f(this);if(a)return a;if(this.o){var a=this.o,b=new FileReader,c=g(b);b.readAsText(a);return c}if(this.i)return Promise.resolve(k(this.i));
if(this.Y)throw Error("could not read FormData body as text");return Promise.resolve(this.J)};z.formData&&(this.formData=function(){return this.text().then(E)});this.json=function(){return this.text().then(JSON.parse)};return this}function m(a,b){b=b||{};var c=b.body;if("string"===typeof a)this.url=a;else{if(a.bodyUsed)throw new TypeError("Already read");this.url=a.url;this.credentials=a.credentials;b.headers||(this.headers=new e(a.headers));this.method=a.method;this.mode=a.mode;c||null==a.s||(c=
a.s,a.bodyUsed=!0)}this.credentials=b.credentials||this.credentials||"omit";if(b.headers||!this.headers)this.headers=new e(b.headers);a=b.method||this.method||"GET";var d=a.toUpperCase();this.method=-1<M.indexOf(d)?d:a;this.mode=b.mode||this.mode||null;this.referrer=null;if(("GET"===this.method||"HEAD"===this.method)&&c)throw new TypeError("Body not allowed for GET or HEAD requests");this.Z(c)}function E(a){var b=new FormData;a.trim().split("&").forEach(function(a){if(a){var c=a.split("=");a=c.shift().replace(/\+/g,
" ");c=c.join("=").replace(/\+/g," ");b.append(decodeURIComponent(a),decodeURIComponent(c))}});return b}function H(a){var b=new e;a.split("\r\n").forEach(function(a){a=a.split(":");var c=a.shift().trim();c&&b.append(c,a.join(":").trim())});return b}function q(a,b){b||(b={});this.type="default";this.status="status"in b?b.status:200;this.ok=200<=this.status&&300>this.status;this.statusText="statusText"in b?b.statusText:"OK";this.headers=new e(b.headers);this.url=b.url||"";this.Z(a)}if(!c.fetch){K();
var z={searchParams:"URLSearchParams"in c,ja:"Symbol"in c&&"iterator"in Symbol,blob:"FileReader"in c&&"Blob"in c&&!0,formData:"FormData"in c,arrayBuffer:"ArrayBuffer"in c};if(z.arrayBuffer)var A="[object Int8Array];[object Uint8Array];[object Uint8ClampedArray];[object Int16Array];[object Uint16Array];[object Int32Array];[object Uint32Array];[object Float32Array];[object Float64Array]".split(";"),w=ArrayBuffer.isView||function(a){return a&&-1<A.indexOf(Object.prototype.toString.call(a))};e.prototype.append=
function(c,d){c=b(c);d=a(d);var e=this.map[c];this.map[c]=e?e+","+d:d};e.prototype["delete"]=function(a){delete this.map[b(a)]};e.prototype.get=function(a){a=b(a);return this.has(a)?this.map[a]:null};e.prototype.has=function(a){return this.map.hasOwnProperty(b(a))};e.prototype.set=function(c,d){this.map[b(c)]=a(d)};e.prototype.forEach=function(a,b){for(var c in this.map)this.map.hasOwnProperty(c)&&a.call(b,this.map[c],c,this)};e.prototype.keys=function(){var a=[];this.forEach(function(b,c){a.push(c)});
return d(a)};e.prototype.values=function(){var a=[];this.forEach(function(b){a.push(b)});return d(a)};e.prototype.entries=function(){var a=[];this.forEach(function(b,c){a.push([c,b])});return d(a)};z.ja&&(K(),L(),e.prototype[Symbol.iterator]=e.prototype.entries);var M="DELETE GET HEAD OPTIONS POST PUT".split(" ");m.prototype.clone=function(){return new m(this,{body:this.s})};n.call(m.prototype);n.call(q.prototype);q.prototype.clone=function(){return new q(this.s,{status:this.status,statusText:this.statusText,
headers:new e(this.headers),url:this.url})};q.error=function(){var a=new q(null,{status:0,statusText:""});a.type="error";return a};var Q=[301,302,303,307,308];q.redirect=function(a,b){if(-1===Q.indexOf(b))throw new RangeError("Invalid status code");return new q(null,{status:b,headers:{location:a}})};c.Headers=e;c.Request=m;c.Response=q;c.fetch=function(a,b){return new Promise(function(c,d){var e=new m(a,b),f=new XMLHttpRequest;f.onload=function(){var a={status:f.status,statusText:f.statusText,headers:H(f.getAllResponseHeaders()||
"")};a.url="responseURL"in f?f.responseURL:a.headers.get("X-Request-URL");c(new q("response"in f?f.response:f.responseText,a))};f.onerror=function(){d(new TypeError("Network request failed"))};f.ontimeout=function(){d(new TypeError("Network request failed"))};f.open(e.method,e.url,!0);"include"===e.credentials&&(f.withCredentials=!0);"responseType"in f&&z.blob&&(f.responseType="blob");e.headers.forEach(function(a,b){f.setRequestHeader(b,a)});f.send("undefined"===typeof e.s?null:e.s)})};c.fetch.gb=
!0}})("undefined"!==typeof self?self:this)}]);
